---
- name: "Creates backend app directory"
  file:
    path: ~/backend
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    npm i


- name: Start the app
  shell: |
    echo export TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js} >> ~/.bashrc
    echo export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}" >> ~/.bashrc
    echo export TYPEORM_PORT=5532 >> ~/.bashrc
    echo export TYPEORM_USERNAME=postgres >> ~/.bashrc
    echo export TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION') }}" >> ~/.bashrc
    echo export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}" >> ~/.bashrc
    echo export TYPEORM_DATABASE=glee >> ~/.bashrc
    echo export TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations >> ~/.bashrc
    echo export TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts >> ~/.bashrc
    echo export NODE_ENV=production >> ~/.bashrc
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js

