---
- name: set env vars
  become: true
  become_user: root
  become_method: sudo
  shell: |
    echo TYPEORM_ENTITIES=./backend/dist/modules/domain/**/*.entity{.ts,.js} >> /etc/environment
    echo TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}" >> /etc/environment
    echo TYPEORM_PORT=5432 >> /etc/environment
    echo TYPEORM_USERNAME=postgres >> /etc/environment
    echo TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION') }}" >> /etc/environment
    echo TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}" >> /etc/environment
    echo TYPEORM_DATABASE=glee >> /etc/environment
    echo TYPEORM_MIGRATIONS_DIR=./backend/dist/migrations >> /etc/environment
    echo TYPEORM_MIGRATIONS=./backend/dist/migrations/*.ts >> /etc/environment
    echo NODE_ENV=production >> /etc/environment
    echo VERSION=1 >> /etc/environment

- name: "Creates backend app directory"
  shell: |    
    mkdir -p /home/ubuntu/backend

- name: "Unarchive backend files"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: "Installing Node Dependencies"
  shell: |
    cd /home/ubuntu/backend
    npm i    

- name: Start the app
  become: true
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js

    

