# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glee
    ports:
      - "5532:5432"
